server:
  port: 3000

spring:
  application:
    name: MyWorkRegistryCenter

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:3000/eureka # ??eureka??